spring:
  application:
    name: api-manicure

  datasource:
    url: jdbc:mysql://square-cloud-db-0b07c3f9849543d9ad112c566890d9b1.squareweb.app:7205/db_manicure_homologacao
    username: squarecloud
    password: W6ANEbP9n9TtDlsF9GCxvsPO
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      max-lifetime: 300000
      keepalive-time: 60000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

  mail:
    host: smtp-relay.brevo.com
    port: 587
    username: matheushard2013@gmail.com
    password: f9tKpFLxP
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

security:
  config:
    prefix: Bearer
    key: SECRET_KEY
    expiration: 3600000

jwt:
  secret: DDDFGFDSKKMMMMMMSAKALSMALDAGHGFJDLEEKEMDSSDADNFGBVVCC
  expiration: 3600000

logging:
  level:
    org:
      springframework:
        security: DEBUG
        web: DEBUG

server:
  port: 8081
  address: 0.0.0.0