spring:
  application:
    name: api-manicure

  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      max-lifetime: 300000
      keepalive-time: 60000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

  mail:
    host: ${SMTP_HOST}
    port: ${SMTP_PORT}
    username: ${SMTP_USER}
    password: ${SMTP_PASS}
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

security:
  config:
    prefix: ${JWT_PREFIX}
    key: ${JWT_KEY}
    expiration: 3600000

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}

logging:
  level:
    org:
      springframework:
        security: DEBUG
        web: DEBUG

server:
  port: ${PORT:80}
  address: 0.0.0.0